//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.UI.Mvc5.Areas.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AreaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AreaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.UI.Mvc5.Areas.Management.AreaResources", typeof(AreaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{PropertyName}&apos; is invalid or does not exist..
        /// </summary>
        public static string _Validation_BlobIdInvalidError {
            get {
                return ResourceManager.GetString("_Validation_BlobIdInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid image file type..
        /// </summary>
        public static string _Validation_BlobImageMimeTypeError {
            get {
                return ResourceManager.GetString("_Validation_BlobImageMimeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a known valid file type..
        /// </summary>
        public static string _Validation_BlobKnownMimeTypeError {
            get {
                return ResourceManager.GetString("_Validation_BlobKnownMimeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has exceeded the upload size limit..
        /// </summary>
        public static string _Validation_BlobSizeLimitError {
            get {
                return ResourceManager.GetString("_Validation_BlobSizeLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail &apos;{PropertyValue}&apos; is already taken by another user..
        /// </summary>
        public static string _Validation_EmailTakenError {
            get {
                return ResourceManager.GetString("_Validation_EmailTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should have a maximum of {MaxLength} characters..
        /// </summary>
        public static string _Validation_MaxLength {
            get {
                return ResourceManager.GetString("_Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should have at least {MinLength} characters..
        /// </summary>
        public static string _Validation_MinLength {
            get {
                return ResourceManager.GetString("_Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string _Validation_PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("_Validation_PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with the terms of use to proceed..
        /// </summary>
        public static string _Validation_TermsAcceptanceError {
            get {
                return ResourceManager.GetString("_Validation_TermsAcceptanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name &apos;{PropertyValue}&apos; is already taken by another user..
        /// </summary>
        public static string _Validation_UserNameTakenError {
            get {
                return ResourceManager.GetString("_Validation_UserNameTakenError", resourceCulture);
            }
        }
    }
}
