//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.UI.Mvc5.Areas.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AreaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AreaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.UI.Mvc5.Areas.Users.AreaResources", typeof(AreaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail &apos;{PropertyValue}&apos; is already taken by another user..
        /// </summary>
        public static string _Validation_EmailTakenError {
            get {
                return ResourceManager.GetString("_Validation_EmailTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string _Validation_PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("_Validation_PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with the terms of use to proceed..
        /// </summary>
        public static string _Validation_TermsAcceptanceError {
            get {
                return ResourceManager.GetString("_Validation_TermsAcceptanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name &apos;{PropertyValue}&apos; is already taken by another user..
        /// </summary>
        public static string _Validation_UserNameTakenError {
            get {
                return ResourceManager.GetString("_Validation_UserNameTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your existing password..
        /// </summary>
        public static string ChangePasswordLeadInfo {
            get {
                return ResourceManager.GetString("ChangePasswordLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string CultureId {
            get {
                return ResourceManager.GetString("CultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date, time and numeric format..
        /// </summary>
        public static string CultureIdHint {
            get {
                return ResourceManager.GetString("CultureIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your information and customize available settings for a better app experience..
        /// </summary>
        public static string EditProfileLeadInfo {
            get {
                return ResourceManager.GetString("EditProfileLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Username.
        /// </summary>
        public static string EmailOrUsername {
            get {
                return ResourceManager.GetString("EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not verified..
        /// </summary>
        public static string EmailVerificationAlertMessage {
            get {
                return ResourceManager.GetString("EmailVerificationAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization Settings.
        /// </summary>
        public static string GlobalizationSettings {
            get {
                return ResourceManager.GetString("GlobalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many login attempts. Please try again later..
        /// </summary>
        public static string LockedInfo {
            get {
                return ResourceManager.GetString("LockedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string LogInCallout {
            get {
                return ResourceManager.GetString("LogInCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered?.
        /// </summary>
        public static string LogInCallout2 {
            get {
                return ResourceManager.GetString("LogInCallout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In!.
        /// </summary>
        public static string LogInCalloutAction {
            get {
                return ResourceManager.GetString("LogInCalloutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file size {0}..
        /// </summary>
        public static string MaxFileSizeInfo {
            get {
                return ResourceManager.GetString("MaxFileSizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat New Password.
        /// </summary>
        public static string NewPassword2 {
            get {
                return ResourceManager.GetString("NewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string Password2 {
            get {
                return ResourceManager.GetString("Password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string PictureBlobId {
            get {
                return ResourceManager.GetString("PictureBlobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Password?.
        /// </summary>
        public static string RecoverPasswordCallout {
            get {
                return ResourceManager.GetString("RecoverPasswordCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email bellow to receive recover instructions..
        /// </summary>
        public static string RecoverPasswordInfo {
            get {
                return ResourceManager.GetString("RecoverPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent!.
        /// </summary>
        public static string RecoverPasswordSuccessInfo {
            get {
                return ResourceManager.GetString("RecoverPasswordSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive an email with further instructions shortly..
        /// </summary>
        public static string RecoverPasswordSuccessInfoDetails {
            get {
                return ResourceManager.GetString("RecoverPasswordSuccessInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture.
        /// </summary>
        public static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        public static string SetNewPassword {
            get {
                return ResourceManager.GetString("SetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification failed. Please try again or request a new token..
        /// </summary>
        public static string SetNewPasswordGeneralError {
            get {
                return ResourceManager.GetString("SetNewPasswordGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string SignUpCallout {
            get {
                return ResourceManager.GetString("SignUpCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Now!.
        /// </summary>
        public static string SignUpCalloutAction {
            get {
                return ResourceManager.GetString("SignUpCalloutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the &lt;a href=&quot;#&quot; class=&quot;terms-link&quot;&gt;terms of use&lt;/a&gt;..
        /// </summary>
        public static string TermsAcceptance {
            get {
                return ResourceManager.GetString("TermsAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZoneId {
            get {
                return ResourceManager.GetString("TimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the time zone you are currently in..
        /// </summary>
        public static string TimeZoneIdHint {
            get {
                return ResourceManager.GetString("TimeZoneIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UICultureId {
            get {
                return ResourceManager.GetString("UICultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported language translations..
        /// </summary>
        public static string UICultureIdHint {
            get {
                return ResourceManager.GetString("UICultureIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters and numbers starting with a letter. Ex.: Johnny5.
        /// </summary>
        public static string UserNameHint {
            get {
                return ResourceManager.GetString("UserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your e-mail address to unlock special features in your account..
        /// </summary>
        public static string VerifyEmailLeadInfo {
            get {
                return ResourceManager.GetString("VerifyEmailLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Now!.
        /// </summary>
        public static string VerifyEmailLink {
            get {
                return ResourceManager.GetString("VerifyEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent!.
        /// </summary>
        public static string VerifyEmailMessageSent {
            get {
                return ResourceManager.GetString("VerifyEmailMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification request sent to &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string VerifyEmailMessageSentLeadInfoTemplate {
            get {
                return ResourceManager.GetString("VerifyEmailMessageSentLeadInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify email. Please try again..
        /// </summary>
        public static string VerifyEmailResponseError {
            get {
                return ResourceManager.GetString("VerifyEmailResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!.
        /// </summary>
        public static string VerifyEmailSuccess {
            get {
                return ResourceManager.GetString("VerifyEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is now verified..
        /// </summary>
        public static string VerifyEmailSuccessLeadInfo {
            get {
                return ResourceManager.GetString("VerifyEmailSuccessLeadInfo", resourceCulture);
            }
        }
    }
}
