//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.UI.Mvc5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.UI.Mvc5.AdminResources", typeof(AdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2017 Thiago A. Schneider..
        /// </summary>
        public static string _App_Copyright {
            get {
                return ResourceManager.GetString("_App_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        public static string _App_Name {
            get {
                return ResourceManager.GetString("_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string _App_NavigationLabel {
            get {
                return ResourceManager.GetString("_App_NavigationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Sidebar.
        /// </summary>
        public static string _App_ToggleSidebarLabel {
            get {
                return ResourceManager.GetString("_App_ToggleSidebarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string _App_Welcome {
            get {
                return ResourceManager.GetString("_App_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{PropertyName}&apos; is invalid or does not exist..
        /// </summary>
        public static string _Validation_BlobIdInvalidError {
            get {
                return ResourceManager.GetString("_Validation_BlobIdInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid image file type..
        /// </summary>
        public static string _Validation_BlobImageMimeTypeError {
            get {
                return ResourceManager.GetString("_Validation_BlobImageMimeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a known valid file type..
        /// </summary>
        public static string _Validation_BlobKnownMimeTypeError {
            get {
                return ResourceManager.GetString("_Validation_BlobKnownMimeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has exceeded the upload size limit..
        /// </summary>
        public static string _Validation_BlobSizeLimitError {
            get {
                return ResourceManager.GetString("_Validation_BlobSizeLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail &apos;{PropertyValue}&apos; is already taken by another user..
        /// </summary>
        public static string _Validation_EmailTakenError {
            get {
                return ResourceManager.GetString("_Validation_EmailTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should have a maximum of {MaxLength} characters..
        /// </summary>
        public static string _Validation_MaxLength {
            get {
                return ResourceManager.GetString("_Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should have at least {MinLength} characters..
        /// </summary>
        public static string _Validation_MinLength {
            get {
                return ResourceManager.GetString("_Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string _Validation_PasswordsDoNotMatchError {
            get {
                return ResourceManager.GetString("_Validation_PasswordsDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with the terms of use to proceed..
        /// </summary>
        public static string _Validation_TermsAcceptanceError {
            get {
                return ResourceManager.GetString("_Validation_TermsAcceptanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name &apos;{PropertyValue}&apos; is already taken by another user..
        /// </summary>
        public static string _Validation_UserNameTakenError {
            get {
                return ResourceManager.GetString("_Validation_UserNameTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsLabel {
            get {
                return ResourceManager.GetString("ActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Alert.
        /// </summary>
        public static string Alerts_AddTitle {
            get {
                return ResourceManager.GetString("Alerts_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts_BoxTitle {
            get {
                return ResourceManager.GetString("Alerts_BoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Details.
        /// </summary>
        public static string Alerts_DetailsTitle {
            get {
                return ResourceManager.GetString("Alerts_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Alert.
        /// </summary>
        public static string Alerts_EditTitle {
            get {
                return ResourceManager.GetString("Alerts_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification required..
        /// </summary>
        public static string Alerts_EmailVerificationAlertMessage {
            get {
                return ResourceManager.GetString("Alerts_EmailVerificationAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load unread alerts summary..
        /// </summary>
        public static string Alerts_LoadUnreadErrorMessage {
            get {
                return ResourceManager.GetString("Alerts_LoadUnreadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Read.
        /// </summary>
        public static string Alerts_MarkAsReadLabel {
            get {
                return ResourceManager.GetString("Alerts_MarkAsReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts_Title {
            get {
                return ResourceManager.GetString("Alerts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not read yet.
        /// </summary>
        public static string Alerts_UnreadLabel {
            get {
                return ResourceManager.GetString("Alerts_UnreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string Auth_InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many login attempts. Please try again later..
        /// </summary>
        public static string Auth_LockedInfo {
            get {
                return ResourceManager.GetString("Auth_LockedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string Auth_LockedTitle {
            get {
                return ResourceManager.GetString("Auth_LockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Auth_LogInCallout {
            get {
                return ResourceManager.GetString("Auth_LogInCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In!.
        /// </summary>
        public static string Auth_LogInCalloutAction {
            get {
                return ResourceManager.GetString("Auth_LogInCalloutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered?.
        /// </summary>
        public static string Auth_LogInCalloutAlternate {
            get {
                return ResourceManager.GetString("Auth_LogInCalloutAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Auth_LogInLabel {
            get {
                return ResourceManager.GetString("Auth_LogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Auth_LogInTitle {
            get {
                return ResourceManager.GetString("Auth_LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Auth_RecoverLabel {
            get {
                return ResourceManager.GetString("Auth_RecoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Password?.
        /// </summary>
        public static string Auth_RecoverPasswordCallout {
            get {
                return ResourceManager.GetString("Auth_RecoverPasswordCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email bellow to receive recover instructions..
        /// </summary>
        public static string Auth_RecoverPasswordInfo {
            get {
                return ResourceManager.GetString("Auth_RecoverPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent!.
        /// </summary>
        public static string Auth_RecoverPasswordSuccessInfo {
            get {
                return ResourceManager.GetString("Auth_RecoverPasswordSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive an email with further instructions shortly..
        /// </summary>
        public static string Auth_RecoverPasswordSuccessInfoDetails {
            get {
                return ResourceManager.GetString("Auth_RecoverPasswordSuccessInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string Auth_RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("Auth_RecoverPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification failed. Please try again or request a new token..
        /// </summary>
        public static string Auth_SetNewPasswordGeneralError {
            get {
                return ResourceManager.GetString("Auth_SetNewPasswordGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail and your new password to proceed..
        /// </summary>
        public static string Auth_SetNewPasswordInfo {
            get {
                return ResourceManager.GetString("Auth_SetNewPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        public static string Auth_SetNewPasswordTitle {
            get {
                return ResourceManager.GetString("Auth_SetNewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string Auth_SetPasswordLabel {
            get {
                return ResourceManager.GetString("Auth_SetPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string Auth_SignUpCallout {
            get {
                return ResourceManager.GetString("Auth_SignUpCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        public static string Auth_SignUpCalloutAction {
            get {
                return ResourceManager.GetString("Auth_SignUpCalloutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Auth_SignUpLabel {
            get {
                return ResourceManager.GetString("Auth_SignUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Auth_SignUpTitle {
            get {
                return ResourceManager.GetString("Auth_SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string CultureId {
            get {
                return ResourceManager.GetString("CultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date, time and numeric format..
        /// </summary>
        public static string CultureId_Hint {
            get {
                return ResourceManager.GetString("CultureId_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentLabel {
            get {
                return ResourceManager.GetString("CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash.
        /// </summary>
        public static string Dash_MenuLabel {
            get {
                return ResourceManager.GetString("Dash_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dash_Title {
            get {
                return ResourceManager.GetString("Dash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string DefaultAttentionTitle {
            get {
                return ResourceManager.GetString("DefaultAttentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string DefaultErrorTitle {
            get {
                return ResourceManager.GetString("DefaultErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed..
        /// </summary>
        public static string DefaultInfoMessage {
            get {
                return ResourceManager.GetString("DefaultInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info!.
        /// </summary>
        public static string DefaultInfoTitle {
            get {
                return ResourceManager.GetString("DefaultInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Data.
        /// </summary>
        public static string DefaultSectionFormLabel {
            get {
                return ResourceManager.GetString("DefaultSectionFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the required form data to proceed..
        /// </summary>
        public static string DefaultSectionFormLeadInfo {
            get {
                return ResourceManager.GetString("DefaultSectionFormLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string DefaultSectionListLabel {
            get {
                return ResourceManager.GetString("DefaultSectionListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the available entries bellow..
        /// </summary>
        public static string DefaultSectionListLeadInfo {
            get {
                return ResourceManager.GetString("DefaultSectionListLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was completed with no errors..
        /// </summary>
        public static string DefaultSuccessMessage {
            get {
                return ResourceManager.GetString("DefaultSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string DefaultSuccessTitle {
            get {
                return ResourceManager.GetString("DefaultSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed but some minor problems occured..
        /// </summary>
        public static string DefaultWarningMessage {
            get {
                return ResourceManager.GetString("DefaultWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string DefaultWarningTitle {
            get {
                return ResourceManager.GetString("DefaultWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected item will be permanently deleted..
        /// </summary>
        public static string DeleteDialogConfirmationMessageTemplate {
            get {
                return ResourceManager.GetString("DeleteDialogConfirmationMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong class=&quot;delete-item-label&quot;&gt;&lt;/strong&gt; will be permanently deleted..
        /// </summary>
        public static string DeleteDialogConfirmationMessageTemplateWithLabel {
            get {
                return ResourceManager.GetString("DeleteDialogConfirmationMessageTemplateWithLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Username.
        /// </summary>
        public static string EmailOrUsername {
            get {
                return ResourceManager.GetString("EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items..
        /// </summary>
        public static string EmptyListInfo {
            get {
                return ResourceManager.GetString("EmptyListInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date &amp; Time.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some useful links.
        /// </summary>
        public static string Errors_ActionsCallout {
            get {
                return ResourceManager.GetString("Errors_ActionsCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Bad request..
        /// </summary>
        public static string Errors_BadRequestMessage {
            get {
                return ResourceManager.GetString("Errors_BadRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Access forbidden..
        /// </summary>
        public static string Errors_ForbiddenMessage {
            get {
                return ResourceManager.GetString("Errors_ForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. Please try again..
        /// </summary>
        public static string Errors_GeneralErrorMessage {
            get {
                return ResourceManager.GetString("Errors_GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! The page was not found..
        /// </summary>
        public static string Errors_NotFoundMessage {
            get {
                return ResourceManager.GetString("Errors_NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Errors_Title {
            get {
                return ResourceManager.GetString("Errors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please log in to proceed!.
        /// </summary>
        public static string Errors_UnauthorizedMessage {
            get {
                return ResourceManager.GetString("Errors_UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features_MenuLabel {
            get {
                return ResourceManager.GetString("Features_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string GoBackToList {
            get {
                return ResourceManager.GetString("GoBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_MenuLabel {
            get {
                return ResourceManager.GetString("Home_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Elements.
        /// </summary>
        public static string HtmlElements_MenuLabel {
            get {
                return ResourceManager.GetString("HtmlElements_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string LogEntriesLabel {
            get {
                return ResourceManager.GetString("LogEntriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest captured log entries..
        /// </summary>
        public static string LogEntriesLabelLeadInfo {
            get {
                return ResourceManager.GetString("LogEntriesLabelLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Logs_AllLabel {
            get {
                return ResourceManager.GetString("Logs_AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Logs_DebugLabel {
            get {
                return ResourceManager.GetString("Logs_DebugLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Logs_ErrorLabel {
            get {
                return ResourceManager.GetString("Logs_ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string Logs_FatalLabel {
            get {
                return ResourceManager.GetString("Logs_FatalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Logs_InfoLabel {
            get {
                return ResourceManager.GetString("Logs_InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        public static string Logs_TraceLabel {
            get {
                return ResourceManager.GetString("Logs_TraceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Logs_TypeLabel {
            get {
                return ResourceManager.GetString("Logs_TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Logs_WarningLabel {
            get {
                return ResourceManager.GetString("Logs_WarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Management_Logs_MenuLabel {
            get {
                return ResourceManager.GetString("Management_Logs_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Management_Logs_Title {
            get {
                return ResourceManager.GetString("Management_Logs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management_MenuLabel {
            get {
                return ResourceManager.GetString("Management_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string Management_Users_AddTitle {
            get {
                return ResourceManager.GetString("Management_Users_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string Management_Users_EditTitle {
            get {
                return ResourceManager.GetString("Management_Users_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Management_Users_MenuLabel {
            get {
                return ResourceManager.GetString("Management_Users_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Management_Users_Title {
            get {
                return ResourceManager.GetString("Management_Users_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created.
        /// </summary>
        public static string Management_Users_UserCreatedMessageSubject {
            get {
                return ResourceManager.GetString("Management_Users_UserCreatedMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file size {0}..
        /// </summary>
        public static string MaxFileSizeInfo {
            get {
                return ResourceManager.GetString("MaxFileSizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string MessageType_Error {
            get {
                return ResourceManager.GetString("MessageType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info!.
        /// </summary>
        public static string MessageType_Info {
            get {
                return ResourceManager.GetString("MessageType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string MessageType_Success {
            get {
                return ResourceManager.GetString("MessageType_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string MessageType_Warning {
            get {
                return ResourceManager.GetString("MessageType_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Confirmation.
        /// </summary>
        public static string NewPassword2 {
            get {
                return ResourceManager.GetString("NewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string Password2 {
            get {
                return ResourceManager.GetString("Password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Actions.
        /// </summary>
        public static string PictureActions {
            get {
                return ResourceManager.GetString("PictureActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string PictureBlobId {
            get {
                return ResourceManager.GetString("PictureBlobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string ScreenAutoLockMinutes {
            get {
                return ResourceManager.GetString("ScreenAutoLockMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Search_AllLabel {
            get {
                return ResourceManager.GetString("Search_AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No detailed description available..
        /// </summary>
        public static string Search_EmptyDescriptionMessage {
            get {
                return ResourceManager.GetString("Search_EmptyDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Search_MediaLabel {
            get {
                return ResourceManager.GetString("Search_MediaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search....
        /// </summary>
        public static string Search_PlaceholderLabel {
            get {
                return ResourceManager.GetString("Search_PlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Search_ResultsTitle {
            get {
                return ResourceManager.GetString("Search_ResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_SearchLabel {
            get {
                return ResourceManager.GetString("Search_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        public static string Search_TypeAlert {
            get {
                return ResourceManager.GetString("Search_TypeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Search_TypeEvent {
            get {
                return ResourceManager.GetString("Search_TypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string Search_TypeUser {
            get {
                return ResourceManager.GetString("Search_TypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date &amp; Time.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks_BoxTitle {
            get {
                return ResourceManager.GetString("Tasks_BoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the &lt;a href=&quot;#&quot; class=&quot;terms-link&quot;&gt;terms of use&lt;/a&gt;..
        /// </summary>
        public static string TermsAcceptance {
            get {
                return ResourceManager.GetString("TermsAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp.
        /// </summary>
        public static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZoneId {
            get {
                return ResourceManager.GetString("TimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the time zone you are currently in..
        /// </summary>
        public static string TimeZoneId_Hint {
            get {
                return ResourceManager.GetString("TimeZoneId_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UICultureId {
            get {
                return ResourceManager.GetString("UICultureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported language translations..
        /// </summary>
        public static string UICultureId_Hint {
            get {
                return ResourceManager.GetString("UICultureId_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserIds {
            get {
                return ResourceManager.GetString("UserIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters and numbers starting with a letter. Ex.: Johnny5.
        /// </summary>
        public static string UserName_Hint {
            get {
                return ResourceManager.GetString("UserName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Calendar.
        /// </summary>
        public static string Users_Calendar {
            get {
                return ResourceManager.GetString("Users_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Users_ChangePasswordLinkLabel {
            get {
                return ResourceManager.GetString("Users_ChangePasswordLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Users_ChangePasswordTitle {
            get {
                return ResourceManager.GetString("Users_ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Users_EditProfileLinkLabel {
            get {
                return ResourceManager.GetString("Users_EditProfileLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Users_EditProfileTitle {
            get {
                return ResourceManager.GetString("Users_EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event File.
        /// </summary>
        public static string Users_EventBlob {
            get {
                return ResourceManager.GetString("Users_EventBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Files.
        /// </summary>
        public static string Users_EventBlobs {
            get {
                return ResourceManager.GetString("Users_EventBlobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files.
        /// </summary>
        public static string Users_EventBlobsSelect {
            get {
                return ResourceManager.GetString("Users_EventBlobsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files uploaded..
        /// </summary>
        public static string Users_EventsNoBlobs {
            get {
                return ResourceManager.GetString("Users_EventsNoBlobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the time zone for this event..
        /// </summary>
        public static string Users_EventTimeZoneIdHint {
            get {
                return ResourceManager.GetString("Users_EventTimeZoneIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string Users_InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("Users_InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string Users_LockScreenLinkLabel {
            get {
                return ResourceManager.GetString("Users_LockScreenLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto lock:.
        /// </summary>
        public static string Users_LockScreenSettingsAutoLabel {
            get {
                return ResourceManager.GetString("Users_LockScreenSettingsAutoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Users_LockScreenSettingsAutoValudeDisabled {
            get {
                return ResourceManager.GetString("Users_LockScreenSettingsAutoValudeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {interval} minutes..
        /// </summary>
        public static string Users_LockScreenSettingsAutoValueTemplate {
            get {
                return ResourceManager.GetString("Users_LockScreenSettingsAutoValueTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string Users_LogOffLinkLabel {
            get {
                return ResourceManager.GetString("Users_LogOffLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Events.
        /// </summary>
        public static string Users_ManageEventsActionLabel {
            get {
                return ResourceManager.GetString("Users_ManageEventsActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Schedule.
        /// </summary>
        public static string Users_MyScheduleLinkLabel {
            get {
                return ResourceManager.GetString("Users_MyScheduleLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events..
        /// </summary>
        public static string Users_NoUpcomingEventsInfo {
            get {
                return ResourceManager.GetString("Users_NoUpcomingEventsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Users_ScheduleEventsAddNewLabel {
            get {
                return ResourceManager.GetString("Users_ScheduleEventsAddNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Event.
        /// </summary>
        public static string Users_ScheduleEventsAddTitle {
            get {
                return ResourceManager.GetString("Users_ScheduleEventsAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event.
        /// </summary>
        public static string Users_ScheduleEventsEditTitle {
            get {
                return ResourceManager.GetString("Users_ScheduleEventsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Schedule Events.
        /// </summary>
        public static string Users_ScheduleEventsTitle {
            get {
                return ResourceManager.GetString("Users_ScheduleEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Schedule.
        /// </summary>
        public static string Users_ScheduleTitle {
            get {
                return ResourceManager.GetString("Users_ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Locked.
        /// </summary>
        public static string Users_ScreenLockedTitle {
            get {
                return ResourceManager.GetString("Users_ScreenLockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture.
        /// </summary>
        public static string Users_SelectPictureLabel {
            get {
                return ResourceManager.GetString("Users_SelectPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Users_UnlockLabel {
            get {
                return ResourceManager.GetString("Users_UnlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not {0}?.
        /// </summary>
        public static string Users_UnlockScreenCalloutTemplate {
            get {
                return ResourceManager.GetString("Users_UnlockScreenCalloutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string Users_UpcomingEvents {
            get {
                return ResourceManager.GetString("Users_UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        public static string Users_VerifyEmailLabel {
            get {
                return ResourceManager.GetString("Users_VerifyEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your e-mail address to unlock special features in your account..
        /// </summary>
        public static string Users_VerifyEmailLeadInfo {
            get {
                return ResourceManager.GetString("Users_VerifyEmailLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Now!.
        /// </summary>
        public static string Users_VerifyEmailLinkLabel {
            get {
                return ResourceManager.GetString("Users_VerifyEmailLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent!.
        /// </summary>
        public static string Users_VerifyEmailMessageSentLabel {
            get {
                return ResourceManager.GetString("Users_VerifyEmailMessageSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification request sent to {0}..
        /// </summary>
        public static string Users_VerifyEmailMessageSentLeadInfoTemplate {
            get {
                return ResourceManager.GetString("Users_VerifyEmailMessageSentLeadInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send verification message. Please try again..
        /// </summary>
        public static string Users_VerifyEmailRequestError {
            get {
                return ResourceManager.GetString("Users_VerifyEmailRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify email. Please try again..
        /// </summary>
        public static string Users_VerifyEmailResponseError {
            get {
                return ResourceManager.GetString("Users_VerifyEmailResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!.
        /// </summary>
        public static string Users_VerifyEmailSuccessLabel {
            get {
                return ResourceManager.GetString("Users_VerifyEmailSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is now verified..
        /// </summary>
        public static string Users_VerifyEmailSuccessLeadInfo {
            get {
                return ResourceManager.GetString("Users_VerifyEmailSuccessLeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        public static string Users_VerifyEmailTitle {
            get {
                return ResourceManager.GetString("Users_VerifyEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_WidgetList {
            get {
                return ResourceManager.GetString("Users_WidgetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string UTCCreation {
            get {
                return ResourceManager.GetString("UTCCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Read.
        /// </summary>
        public static string UTCRead {
            get {
                return ResourceManager.GetString("UTCRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
